server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          # 代理的服务地址;lb表示从eureka中获取具体服务
          #uri: http://127.0.0.1:9091
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - MyParam=name

      default-filters:
        - AddResponseHeader=X-Response-Default-MyName, zvspcloud

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true