server:
  port: ${port:9091}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhangwei
  application:
    name: user-service
mybatis:
  type-aliases-package: com.stuspcloud.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    #更倾向于IP地址
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #续约间隔 默认30S
    lease-renewal-interval-in-seconds: 5
    #服务失效时间 默认90S
    lease-expiration-duration-in-seconds: 5