
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #定时拉取服务时间间隔
    registry-fetch-interval-seconds: 10
spring:
  application:
    name: consumer-demo
#配置熔断为两秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
ribbon: #Feign自带配置
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试
feign:
  hystrix:
    enabled: true #开启feign的hystrix的功能
logging:
  level:
    com.stuspcloud: debug